fix bug related to argument and output
AlphaGenes/AlphaPeel pull request #157
Opened 2024-01-11 17:53 UTC by AprilYUZhang

2024-01-11 18:08 UTC, gregorgorjanc commented on src/tinypeel/Peeling/PeelingIO.py
> +            writeCalledGenotypes(
if args.geno:
         if args.geno_threshold:
             for thresh in args.geno_threshold:
                 if thresh < 1 / 3:
                     thresh = 1 / 3
         else:
             thresh = 1 / 3

         if args.binary_call_file:
             writeBinaryCalledGenotypes(
                pedigree,
                genoProbFunc,
                isSexChrom,
                args.out_file + ".called." + str(thresh),
                thresh,
             )
         else:
            writeCalledGenotypes(
  ...
```

Do you see what I have done here?

2024-01-11 18:09 UTC, gregorgorjanc commented on src/tinypeel/Peeling/PeelingIO.py
> +        if args.hap_threshold:
@AprilYUZhang As above

2024-01-11 18:09 UTC, gregorgorjanc requested changes
@AprilYUZhang thanks for this fix! I have one proposed change and then this is ready to be merged in! Fab;)

2024-01-12 10:27 UTC, gregorgorjanc commented on src/tinypeel/Peeling/PeelingIO.py
> +            writeCalledGenotypes(
```
if args.geno:
 TODO: improve this top part
         treshs = [] 
         if len(args.geno_threshold) > 0:
             for thresh in args.geno_threshold:
                 if thresh < 1 / 3:
                     threshs.append(1 / 3)
         else:
             threshs = 1 / 3

        for tresh in treshs:
           if args.binary_call_file:
               writeBinaryCalledGenotypes(
                  pedigree,
                  genoProbFunc,
                  isSexChrom,
                  args.out_file + ".called." + str(thresh),
                  thresh,
               )
           else:
              writeCalledGenotypes(
  ...
```

2024-08-16 12:56 UTC, XingerTang commented
@AprilYUZhang Why this pull request is closed before merging in?

2024-08-20 11:06 UTC, AprilYUZhang commented
I completely forgot why, but it should be merged in principle. So I reopened.

2024-10-22 08:30 UTC, gregorgorjanc commented
@AprilYUZhang @XingerTang this PR is now openned for a long time. Remind me where we stand with this one?

2024-10-22 08:45 UTC, XingerTang commented
@gregorgorjanc This PR is ready to merge. :)

2024-10-22 09:46 UTC, gregorgorjanc approved these changes
LGTM!

2024-10-22 09:52 UTC, merged