Add changelog #87
AlphaGenes/AlphaPeel pull request #158
Opened 2024-01-11 18:19 UTC by XingerTang

#87

Adapted from numpy's [changelog](https://github.com/numpy/numpy/tree/fff44a72355915165fdc1c51b371fd5f908680b9/doc/changelog), [upcoming changes](https://github.com/numpy/numpy/tree/fff44a72355915165fdc1c51b371fd5f908680b9/doc/release/upcoming_changes), and [release notes](https://github.com/numpy/numpy/tree/fff44a72355915165fdc1c51b371fd5f908680b9/doc/release/upcoming_changes).

The reason for using the templates and structures from Numpy instead of msprime is that Numpy also builds the documentation using Sphinx, while msprime builds the documentation in its own way. So Numpy is using `.rst` files while msprime is using `.md` file. As we are using `.rst` and Sphinx now, I think it is better to follow what Numpy did. 

The preview for the release notes page of the updated documentation is available at https://xingertang-alphapeel.readthedocs.io/en/latest/release/1.2.0-notes.html.

As Numpy did not put changelog and upcoming changes inside its documentation, I also didn't add it, but we can change it if necessary.

2024-01-11 20:35 UTC, gregorgorjanc commented on docs/release/upcoming_changes/README.rst
Is this where we will put things before they go onto version release notes? Maybe we just work with version release notes file (numpy is a much larger project so they need to announce changes)

2024-01-11 20:37 UTC, gregorgorjanc commented on docs/release/upcoming_changes/154.new_feature.rst
Move to release notes file - for simplicity

2024-01-11 20:39 UTC, gregorgorjanc requested changes
@XingerTang minor comments. This looks fantastic otherwise. I wonder if it’s almost too much, but time will tell! I like it. Now we just need to ensure we build it gradually with each PR!

2024-01-23 06:36 UTC, gregorgorjanc approved these changes
Looks good

2024-10-22 08:31 UTC, gregorgorjanc commented
@XingerTang I lost track on this PR too. Should we merge in and work from this point onwards?

2024-10-22 08:47 UTC, XingerTang commented
@gregorgorjanc I think it might be because the changes are still ongoing so we can't finish it until all the changes have completed.

2024-10-22 09:45 UTC, gregorgorjanc commented
@XingerTang I am thinking that we should be growing changelog with each new major PR/change so that we don't have these multiple PR open and wondering what needs doing in each one.

What are the major things that we are currently working on? Please list these in the changelog as work in progress and then we merge this in, and update the changelog when those work in progress PR/changes are merged into the devel branch.

2024-10-30 08:43 UTC, gregorgorjanc commented
- [ ] @XingerTang @RosCraddock please add an entry to Changelog regarding metafounder functionality

2025-05-05 14:58 UTC, closed without merging